### ISSUE TITLE
feature:添加开学注册和放假的时间

### ISSUE THREAD

**Issue by Gsllchb** [Trim21/sdu2ics#1]
放假和开学时间学校官网上应该有。

**Comment by trim21** [comment]
其实我硬编码到代码里去了。。

**Comment by trim21** [comment]
你指的是小假期吗？

**Comment by Gsllchb** [comment]
不是小假期 是寒暑假

**Comment by trim21** [comment]
其实是有硬编码的。。
你是希望多一个日历事件吗？
校历给的放假时间是这样的
>考试：
6月26日至7月9日。

7月9号是晚于实际放假时间的，没有什么参照意义

**Comment by Gsllchb** [comment]
那不如这样吧。添加开学注册时间和考试时间。

**Comment by trim21** [comment]
教务系统现在没开考试时间查询，我现在没法添加这个功能。。。

**Comment by trim21** [comment]
顺便，我的教务系统里面的课表现在空了，你的课表也这样了吗

**Comment by Gsllchb** [comment]
虽然教务系统没有，但是官网上的校历好像有这些时间。我的课表也空了。。。。

**Comment by Gsllchb** [comment]
官网校历里还有运动会的时间，这个也加进去吧。。。

**Comment by trim21** [comment]
欢迎你加完了提PR（

**Comment by Gsllchb** [comment]
。。。。我不打算自己写啊。。。我就是提一下建议

**Comment by trim21** [comment]
那只能期待有人写了提pr了，我也不准备写😂

2017-05-27 21:08 GMT+08:00 Gsllchb <notifications@github.com>:

> 。。。。我不打算自己写啊。。。我就是提一下建议
>

**Comment by Gsllchb** [comment]
......估计没人会去写了。。我什么时候有空了写一写吧。。毕竟还没玩过爬虫

**Comment by trim21** [comment]
考试查询已经开放了

**Comment by trim21** [comment]
现在需要修改日历连接，重新订阅
