### ISSUE TITLE
safari无法添加日历

### ISSUE THREAD

**Issue by Gsllchb** [Trim21/sdu2ics#2]
账号和密码均输入正确。
safari提示：
download failed
safari cannot download this file

**Comment by trim21** [comment]
因为现在教务系统的课表是空的..这个bug我还没修复..

**Comment by Gsllchb** [comment]
原本我还想添加考试安排的。。

**Comment by trim21** [comment]
这没什么影响吧..你设置一个新的路由,用一个新的parser就可以了

**Comment by trim21** [comment]
现在回头看一眼发现代码我自己已经看不懂了....等考完试我重构一下加上注释吧....
随手抓了一下考试安排的包,虽然直接返回的就是json,但是进行请求的数据非常复杂...

**Comment by trim21** [comment]
考试安排已经添加,链接发生了变化,需要重新手动添加日历
